declare const raritySchema: {
    readonly common: {
        readonly unboxingWeight: 40000000;
        readonly rarityUpgradeTier: 0;
        readonly smashDropMultiplier: 1;
        readonly baseTallyCap: 500;
        readonly collectorsRequirement: 200;
        readonly tourValueMultiplier: 0.5;
        readonly color: "#4d950f";
        readonly baseSigilSlots: 4;
        readonly prefixAccentuation: 1;
        readonly tallyMaxFlavors: ["Completely Catalogued"];
        readonly name: "Common";
        readonly borderImage: "/tooltipbgs/common.png";
        readonly slatedValueReduction: 0.3;
    };
    readonly uncommon: {
        readonly unboxingWeight: 35000000;
        readonly rarityUpgradeTier: 0;
        readonly smashDropMultiplier: 1.4;
        readonly baseTallyCap: 1000;
        readonly collectorsRequirement: 180;
        readonly tourValueMultiplier: 0.5;
        readonly color: "#293f14";
        readonly baseSigilSlots: 4;
        readonly prefixAccentuation: 1;
        readonly tallyMaxFlavors: ["Melancholically Marked"];
        readonly name: "Uncommon";
        readonly borderImage: "/tooltipbgs/uncommon.png";
        readonly slatedValueReduction: 0.4;
    };
    readonly rare: {
        readonly unboxingWeight: 20000000;
        readonly rarityUpgradeTier: 0;
        readonly smashDropMultiplier: 1.8;
        readonly baseTallyCap: 1000;
        readonly collectorsRequirement: 160;
        readonly tourValueMultiplier: 0.6;
        readonly color: "#468586";
        readonly baseSigilSlots: 5;
        readonly prefixAccentuation: 1;
        readonly tallyMaxFlavors: ["Indubitably Itemized"];
        readonly name: "Rare";
        readonly borderImage: "/tooltipbgs/rare.png";
        readonly slatedValueReduction: 0.5;
    };
    readonly epic: {
        readonly unboxingWeight: 10000000;
        readonly rarityUpgradeTier: 0;
        readonly smashDropMultiplier: 2.2;
        readonly baseTallyCap: 1000;
        readonly collectorsRequirement: 120;
        readonly tourValueMultiplier: 0.7;
        readonly color: "#741a62";
        readonly baseSigilSlots: 5;
        readonly prefixAccentuation: 1.1;
        readonly tallyMaxFlavors: ["Reasonably Registered"];
        readonly name: "Epic";
        readonly borderImage: "/tooltipbgs/epic.png";
        readonly slatedValueReduction: 0.6;
    };
    readonly legendary: {
        readonly unboxingWeight: 5000000;
        readonly rarityUpgradeTier: 1;
        readonly smashDropMultiplier: 2.5;
        readonly baseTallyCap: 5000;
        readonly collectorsRequirement: 80;
        readonly tourValueMultiplier: 0.8;
        readonly color: "#ee39bb";
        readonly baseSigilSlots: 5;
        readonly prefixAccentuation: 1.2;
        readonly tallyMaxFlavors: ["Decidedly Doomed"];
        readonly name: "Legendary";
        readonly borderImage: "/tooltipbgs/legendary.png";
        readonly slatedValueReduction: 0.7;
    };
    readonly relic: {
        readonly unboxingWeight: 3000000;
        readonly rarityUpgradeTier: 2;
        readonly smashDropMultiplier: 2.7;
        readonly baseTallyCap: 15000;
        readonly collectorsRequirement: 75;
        readonly tourValueMultiplier: 0.7;
        readonly color: "#cc0000";
        readonly baseSigilSlots: 5;
        readonly prefixAccentuation: 1.3;
        readonly tallyMaxFlavors: ["Eldenly Estimated"];
        readonly name: "Relic";
        readonly borderImage: "/tooltipbgs/relic.png";
        readonly slatedValueReduction: 0.8;
    };
    readonly cubic: {
        readonly unboxingWeight: 400000;
        readonly rarityUpgradeTier: 3;
        readonly smashDropMultiplier: 4.3;
        readonly baseTallyCap: 50000;
        readonly collectorsRequirement: 50;
        readonly tourValueMultiplier: 0.7;
        readonly color: "#2e2e2e";
        readonly baseSigilSlots: 5;
        readonly prefixAccentuation: 1.6;
        readonly tallyMaxFlavors: ["Admittedly Arduous"];
        readonly name: "Cubic";
        readonly borderImage: "/tooltipbgs/cubic.png";
        readonly slatedValueReduction: 0.9;
    };
    readonly special: {
        readonly unboxingWeight: 350000;
        readonly rarityUpgradeTier: 0;
        readonly smashDropMultiplier: 1;
        readonly baseTallyCap: 1;
        readonly collectorsRequirement: 140;
        readonly tourValueMultiplier: 0.5;
        readonly color: "#70aeff";
        readonly baseSigilSlots: 7;
        readonly prefixAccentuation: 1;
        readonly tallyMaxFlavors: ["Resplendently Reckoned"];
        readonly name: "Special";
        readonly borderImage: "/tooltipbgs/special.png";
        readonly slatedValueReduction: 0.8;
    };
    readonly gold: {
        readonly unboxingWeight: 10000;
        readonly rarityUpgradeTier: 4;
        readonly smashDropMultiplier: 6;
        readonly baseTallyCap: 250000;
        readonly collectorsRequirement: 10;
        readonly tourValueMultiplier: 0.6;
        readonly color: "#ebc634";
        readonly baseSigilSlots: 5;
        readonly prefixAccentuation: 2.2;
        readonly tallyMaxFlavors: ["Expensively Encompassed"];
        readonly name: "Gold";
        readonly borderImage: "/tooltipbgs/gold.png";
        readonly slatedValueReduction: 0.9;
    };
    readonly unreal: {
        readonly unboxingWeight: 100;
        readonly rarityUpgradeTier: 5;
        readonly smashDropMultiplier: 100;
        readonly baseTallyCap: 1250000;
        readonly collectorsRequirement: 3;
        readonly tourValueMultiplier: 0.1;
        readonly color: "#240e0e";
        readonly baseSigilSlots: 5;
        readonly prefixAccentuation: 3.2;
        readonly tallyMaxFlavors: ["Mythically Marked"];
        readonly name: "Unreal";
        readonly borderImage: "/tooltipbgs/unreal.png";
        readonly slatedValueReduction: 0.1;
    };
    readonly divine: {
        readonly unboxingWeight: 0;
        readonly rarityUpgradeTier: 0;
        readonly smashDropMultiplier: 25;
        readonly baseTallyCap: 150000;
        readonly collectorsRequirement: 999;
        readonly tourValueMultiplier: 0.1;
        readonly color: "#ffffff";
        readonly baseSigilSlots: 5;
        readonly prefixAccentuation: 6.3;
        readonly tallyMaxFlavors: ["Purely Parted"];
        readonly name: "Divine";
        readonly borderImage: "/tooltipbgs/divine.png";
        readonly slatedValueReduction: 1;
    };
    readonly slated: {
        readonly unboxingWeight: 0;
        readonly rarityUpgradeTier: 0;
        readonly smashDropMultiplier: 25;
        readonly baseTallyCap: 150000;
        readonly collectorsRequirement: 999;
        readonly tourValueMultiplier: 0.1;
        readonly color: "#213047";
        readonly baseSigilSlots: 5;
        readonly prefixAccentuation: 1;
        readonly tallyMaxFlavors: ["Disgustingly Designated"];
        readonly name: "Slated";
        readonly borderImage: "/tooltipbgs/slated.png";
        readonly slatedValueReduction: 1;
    };
    readonly coldiv: {
        readonly unboxingWeight: 0;
        readonly rarityUpgradeTier: 0;
        readonly smashDropMultiplier: 40;
        readonly baseTallyCap: 750000;
        readonly collectorsRequirement: 999;
        readonly tourValueMultiplier: 0.3;
        readonly color: "#660808";
        readonly baseSigilSlots: 5;
        readonly prefixAccentuation: number;
        readonly tallyMaxFlavors: ["Gleefully Gapped"];
        readonly cannotDropSpecialMaterials: true;
        readonly name: "Collector's Divine";
        readonly borderImage: "/tooltipbgs/coldiv.png";
        readonly slatedValueReduction: 1;
    };
    readonly colslat: {
        readonly unboxingWeight: 0;
        readonly rarityUpgradeTier: 0;
        readonly smashDropMultiplier: 40;
        readonly baseTallyCap: 750000;
        readonly collectorsRequirement: 999;
        readonly tourValueMultiplier: 0.3;
        readonly color: "#660808";
        readonly baseSigilSlots: 5;
        readonly prefixAccentuation: number;
        readonly tallyMaxFlavors: ["Nastily Noticeable"];
        readonly cannotDropSpecialMaterials: true;
        readonly name: "Collector's Slated";
        readonly borderImage: "/tooltipbgs/colslat.png";
        readonly slatedValueReduction: 0.9;
    };
    readonly collectors: {
        readonly unboxingWeight: 0;
        readonly rarityUpgradeTier: 0;
        readonly smashDropMultiplier: 12;
        readonly baseTallyCap: 500000;
        readonly collectorsRequirement: 999;
        readonly tourValueMultiplier: 0.3;
        readonly color: "#660808";
        readonly baseSigilSlots: 3;
        readonly prefixAccentuation: number;
        readonly tallyMaxFlavors: ["Completely Comprised"];
        readonly cannotDropSpecialMaterials: true;
        readonly name: "Collector's";
        readonly borderImage: "/tooltipbgs/collectors.png";
        readonly slatedValueReduction: 1;
    };
    readonly exotic: {
        readonly unboxingWeight: 0;
        readonly rarityUpgradeTier: 4000;
        readonly smashDropMultiplier: 1;
        readonly baseTallyCap: 500000;
        readonly collectorsRequirement: 10;
        readonly tourValueMultiplier: 0.5;
        readonly color: "#84b512";
        readonly baseSigilSlots: 5;
        readonly prefixAccentuation: 2.6;
        readonly tallyMaxFlavors: ["Foreignly Figured"];
        readonly name: "Exotic";
        readonly borderImage: "/tooltipbgs/exotic.png";
        readonly slatedValueReduction: 0.5;
    };
    readonly crafted: {
        readonly unboxingWeight: 0;
        readonly rarityUpgradeTier: 0;
        readonly smashDropMultiplier: 20;
        readonly baseTallyCap: 999999999;
        readonly collectorsRequirement: 15;
        readonly tourValueMultiplier: 0.5;
        readonly color: "#4a2c1c";
        readonly baseSigilSlots: 3;
        readonly prefixAccentuation: 1.5;
        readonly tallyMaxFlavors: ["Deliberately Determined"];
        readonly cannotDropSpecialMaterials: true;
        readonly name: "Shop Item";
        readonly borderImage: "/tooltipbgs/crafted.png";
        readonly slatedValueReduction: 0.8;
    };
    readonly materialcube: {
        readonly unboxingWeight: 3000000;
        readonly rarityUpgradeTier: 0;
        readonly smashDropMultiplier: 2;
        readonly baseTallyCap: 1;
        readonly collectorsRequirement: 100;
        readonly tourValueMultiplier: 1;
        readonly color: "#787878";
        readonly baseSigilSlots: 3;
        readonly prefixAccentuation: 0;
        readonly tallyMaxFlavors: ["Partly Premeditated"];
        readonly name: "Material";
        readonly borderImage: "/tooltipbgs/materialcube.png";
        readonly slatedValueReduction: 0.9;
    };
    readonly contraband: {
        readonly unboxingWeight: 0;
        readonly rarityUpgradeTier: 0;
        readonly smashDropMultiplier: 1;
        readonly baseTallyCap: 500000;
        readonly collectorsRequirement: 1000;
        readonly tourValueMultiplier: 1;
        readonly color: "#574000";
        readonly baseSigilSlots: 1;
        readonly prefixAccentuation: 1;
        readonly tallyMaxFlavors: ["Remarkably Marked"];
        readonly name: "Contraband";
        readonly borderImage: "/tooltipbgs/contraband.png";
        readonly slatedValueReduction: 0.1;
    };
    readonly mythic: {
        readonly unboxingWeight: 50;
        readonly rarityUpgradeTier: 0;
        readonly smashDropMultiplier: 1;
        readonly baseTallyCap: 1000000;
        readonly collectorsRequirement: 101;
        readonly tourValueMultiplier: 1;
        readonly color: "#f2b3f2";
        readonly baseSigilSlots: 0;
        readonly prefixAccentuation: 7;
        readonly tallyMaxFlavors: ["Splendidly Specified"];
        readonly name: "Mythical";
        readonly borderImage: "/tooltipbgs/mythical.png";
        readonly slatedValueReduction: 0.5;
    };
};
type RarityID = keyof typeof raritySchema;
declare const allRarities: RarityID[];
export { raritySchema, allRarities, type RarityID };
//# sourceMappingURL=rarities.d.ts.map